# Site settings
title: Thursday Church
email: jay@thursdaychurch.org
description: "Doing church differently"
baseurl: ""
url: "{{ 'assets/css/style.css' | relative_url }}"
twitter_username: Thursday Church
github_username:  Thursday Church

# Build settings
destination: ./public
markdown: kramdown
exclude: [bower.json, bower_components, Gruntfile.js, node_modules, package.json, TODO.txt, SETUP.md]
include: ['_pages']
