# Site settings
title: Faith Promise Church
email: bradr@faithpromise.org
description: "A contemporary church with locations in Knoxville, Maryville, Clinton, and La Follette, TN"
baseurl: ""
url: "http://faithpromise.org"
twitter_username: faithpromise
github_username:  faithpromise

# Build settings
destination: ./public
markdown: kramdown
exclude: [bower.json, bower_components, Gruntfile.js, node_modules, package.json]
include: ['_pages']

# Collections
collections:
  campuses:
    output: false
  teams:
    output: false
  missions:
    output: false
  staff:
    output: true
    permalink: /staff/:path/
  events:
    output: true
    permalink: /events/:path/
  series:
    output: true
    permalink: /series/:path/
