# Site settings
title: Faith Promise Church
email: bradr@faithpromise.org
description: "A contemporary church with locations in Knoxville, Maryville, Clinton, and La Follette, TN"
baseurl: ""
url: "http://faithpromise.org"
twitter_username: faithpromise
github_username:  faithpromise

# Build settings
destination: ./public
markdown: kramdown
exclude: [bower.json, bower_components, Gruntfile.js, node_modules, package.json, TODO.txt, SETUP.md]
include: ['_pages']

# Collections
collections:
  campuses:
    output: true
    permalink: /locations/:path/
  teams:
    output: false
  missions:
    output: false
  staff:
    output: true
    permalink: /staff/:path/
  ministries:
    output: true
    permalink: /:path/
  events:
    output: true
    permalink: /events/:path/
  series:
    output: true
    permalink: /series/:path/
  videos:
    output: true
  topics:
    output: true
    permalink: /topics/:path/
  redirects:
    output: true

# URLS
urls:
  home: /
  staff: /staff/
  events: /events/
  series: /series/
  mp3: //fpcresources.org/audio/

paths:
  images: /build/images/
  series_images: /build/images/series/
  staff_images: /build/images/staff/
