# Site settings
title: Mountain Valley Church of God
email: jay@thursdaychurch.org
description: ""
baseurl: ""
url: "{{ '/' | relative_url }}"
twitter_username: 
github_username:  

# Build settings
destination: ./public
markdown: kramdown
exclude: [bower.json, bower_components, Gruntfile.js, node_modules, package.json, TODO.txt, SETUP.md]
include: ['_pages']
