# Site settings
title: Faith Promise Church
email: bradr@faithpromise.org
description: "A contemporary church with locations in Knoxville, Maryville, Clinton, and La Follette, TN"
baseurl: ""
url: "http://faithpromise.org"
twitter_username: faithpromise
github_username:  faithpromise

# Build settings
markdown: kramdown
